apiVersion: v1
appVersion: "1.1.0"
version: "1.1.0"
name: cert-manager-webhook-infoblox
description: |
  cert-manager webhook for resolving DNS01 challenges using Infoblox. Tested with the following versions: cert-manager v1.16.2, kubernetes v1.30.5+rke2r1, Infoblox GRID: 8.6.2, Infoblox WAPI: 2.8
keywords:
  - cert-manager
  - letsencrypt
  - infoblox
  - webhook
  - acme
  - dns
home: https://github.com/tazthemaniac/cert-manager-webhook-infoblox/
sources:
  - https://github.com/tazthemaniac/cert-manager-webhook-infoblox/